url = https://coalmandi-kpo.rokkun.dev/login

browser = chrome

#kpo login
kpoemail = sandeep+rajastankpo@rokkun.io
#kpoemail = sandeep+kpoteam@rokkun.io
password = Coal@123


# Left navigation bar feature name
sidebardashboardname = dashboard
sidebarteamname = team
sidebarcontractname = contract
sidebarvendorname = vendor
sidebarreportname = reports

# Team management
searchbyname = mahesh
statusname = Active

# create kpo team management 
fullname = sandeep
emailID = sandeep+executive05@rokkun.io
phonenumber = 9663493546

# update kpo team management
updatefullname = mahesh
updateemailID = sandeep+updateexecutive01@rokkun.io
updatephonenumber = 8765435676

#kpo contract management
searchbusinessname = GOOGLE
Statusoptionname =In Progress
statusname = Pending Signature

statuspendingsignature = Pending Signature
#Pending Signature, Pending Release


kpoexecutivename = sandeep
contractbuyersignoptionname = sandeepsyc
contractsellersignoptionname = sandeep trader

#kpo vendor coordination 
searchbybusinessname = ELECTRONICS



